image: rust:latest

pipelines:
  default:
    - step:
        caches:
          - cargo-home
          - cargo-target
        script: # Modify the commands below to build your repository.
          - cargo build -v
          - cargo test -v
definitions:
  caches:
    cargo-home: $HOME/.cargo
    cargo-target: target
